AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ETLCO2:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: etl_co2
      Runtime: python3.11
      Handler: etl_co2.lambda_handler  # Aggiungi entry point
      Code: { S3Bucket: YOUR_BUCKET, S3Key: etl_co2.zip }
      Timeout: 300
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
# Aggiungi Temperature e CarbonIntensity
  EventRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: rate(1 day)
      Targets:
        - Arn: !GetAtt ETLCO2.Arn
          Id: "TriggerETLCO2"
Parameters:
  DatabaseUrl:
    Type: String
